// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBylpYPHhZMaOk_sLvMP2vDtC7KWc-F2SU',
    appId: '1:306397461827:web:4768ef1f489e85a86683f6',
    messagingSenderId: '306397461827',
    projectId: 'mealplanner-96df0',
    authDomain: 'mealplanner-96df0.firebaseapp.com',
    storageBucket: 'mealplanner-96df0.firebasestorage.app',
    measurementId: 'G-PF3JX9LLJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnFmwGaE_IHO7lIjP3B-u7uga8zfDJAs',
    appId: '1:306397461827:android:c524901b64adaccf6683f6',
    messagingSenderId: '306397461827',
    projectId: 'mealplanner-96df0',
    storageBucket: 'mealplanner-96df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyo0wLAuxQQEuzBctrjt74PoV-_xu5BcQ',
    appId: '1:306397461827:ios:5f5d79a90784ce6a6683f6',
    messagingSenderId: '306397461827',
    projectId: 'mealplanner-96df0',
    storageBucket: 'mealplanner-96df0.firebasestorage.app',
    iosBundleId: 'com.example.mealplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyo0wLAuxQQEuzBctrjt74PoV-_xu5BcQ',
    appId: '1:306397461827:ios:5f5d79a90784ce6a6683f6',
    messagingSenderId: '306397461827',
    projectId: 'mealplanner-96df0',
    storageBucket: 'mealplanner-96df0.firebasestorage.app',
    iosBundleId: 'com.example.mealplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBylpYPHhZMaOk_sLvMP2vDtC7KWc-F2SU',
    appId: '1:306397461827:web:b3aa922652d26b296683f6',
    messagingSenderId: '306397461827',
    projectId: 'mealplanner-96df0',
    authDomain: 'mealplanner-96df0.firebaseapp.com',
    storageBucket: 'mealplanner-96df0.firebasestorage.app',
    measurementId: 'G-FH24N0DSE8',
  );
}
